[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
contract = "4r6tCfcZddGA72vHBoCSB35oCYu7Ftqr3E7Psy2bfj8V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
