[toolchain]

[features]
resolution = true
skip-lint = false
seeds = false

[programs.devnet]
ridechain = "C2nZ3sznZgLTZA8zhAgzYXY9aFDo1eEHioUxnaocMm8d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "C:\\Users\\User\\devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
